### ISSUE TITLE
Error: attempting to use a disconnected port object

### ISSUE THREAD

**Issue by terencode** [otommod/chrome-mpris2#12]
The extension is not working anymore:
![image](https://user-images.githubusercontent.com/12665563/44402711-dee12b00-a552-11e8-9786-9577923678dd.png)

**Comment by otommod** [comment]
Can't reproduce.  Is there any relevant output in `.xsession-errors`, if you have that file?  Otherwise, try running chrome from a console (must be a new session).

**Comment by terencode** [comment]
Closing, I was installing it using the ~/bin and not ~/bin/chrome-mpris2.
Maybe it would be easier for the user to just specify the dir, and also less error prone for wrong name if you always check for a file named 'chrome-mpris2' ?
