### ISSUE TITLE
Unable to invoke extension

### ISSUE THREAD

**Issue by mstarodub** [otommod/chrome-mpris2#14]
I'm using a patched version of Chromium on Unity and followed the installation instructions, and still can't seem to get this extension to work. 

Excuse me for the lack of details, please tell me what kind of logs/output would be helpful, so that I can provide the necessary information.

Below is the error the browser console is printing when pressing Play/Pause on a video.
![youtube_mpris_error](https://user-images.githubusercontent.com/23422754/47181620-c22f5c80-d323-11e8-8bc5-6c76ca3dd29c.png)

**Comment by mstarodub** [comment]
I think the issue is not in the extension, apologies.
The mpris interface shows up in KDEconnect (and I can control youtube properly from there), but not on the PC itself.
So the issue is just that it doesn't show in Unity's sound menu. Any ideas how I could add it to there?
I tried putting 'chromium' and 'youtube' into the 'interested media players' menu entry in dconf-editor (currently I have mpd and mpv there, and their entries are 'mpd-sound-menu.desktop' and 'mpv'), but neither works.

**Comment by otommod** [comment]
I honestly can't help you.  I've also had problems using GNOME, I'm using gnome-settings-daemon along with awesomewm and the media-keys component of gsd is also having problem finding the player for some reason... I remember finding a relevant issue which hadn't been solved.  My solution was to just stop using that component :stuck_out_tongue:

**Comment by terencode** [comment]
@otommod did you replace the media-keys component by something else?

**Comment by otommod** [comment]
Ping; anything changed here?

@terencode 	I've bind the media keys (`XF86AudioPlay` etc) through awesome to run [playerctl](https://github.com/acrisci/playerctl).

**Comment by mstarodub** [comment]
@otommod I couldn't get it to work, and if I had to take a guess, changing the gnome configuration entry still seems like the most promising way to approach this.

Maybe you have an idea what the necessary string to add into the highlighted array is?

![interested_players](https://user-images.githubusercontent.com/23422754/51145549-70c83800-1854-11e9-82a4-504a6b84275e.png)

**Comment by otommod** [comment]
@mstarodub Sorry, haven't really used Ubuntu in ages.

**Comment by mstarodub** [comment]
Closing this. solution: don't use Unity/Gnome
