### ISSUE TITLE
Chrome extension fails to load

### ISSUE THREAD

**Issue by pacho2** [otommod/chrome-mpris2#19]
I get this error:
Error in event handler for (unknown): Error: Attempting to use a disconnected port object
background.js:16 (función anónima) (anonymous function)
        programPort.postMessage(msg); -> is highlighted in the error report at extensions section in Google Chrome

Thanks

**Comment by otommod** [comment]
Have you installed companion program? Try running chrome/chromium from a terminal (there must not be another window running) and see if anything weird (specifically, a Python exception) pops up in the logs.

**Comment by pacho2** [comment]
Sorry for the delay :/

Indeed I see this in the terminal:
LaunchProcess: failed to execvp:
/home/pacho/bin/

But I have the executable there:
$ ls -l /home/pacho/bin/chrome-mpris2 
-rwxr-xr-x 1 pacho pacho 16794 sep  5 10:31 /home/pacho/bin/chrome-mpris2

**Comment by YasserRabee** [comment]
I came across the same problem. it seems like the steps to install on the README are not easy enough for average user. I followed steps from [here](https://www.linuxuprising.com/2018/08/add-youtube-player-controls-to-your.html?m=1) and it works fine with me
