### ISSUE TITLE
Shared upstream

### ISSUE THREAD

**Issue by orschiro** [otommod/chrome-mpris2#2]
Hey @otommod,

Thanks for this promising development!

I [shared your repo with upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=267590&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=).

Let's hope they integrate mpris2 into official Chromium. :-)

**Comment by otommod** [comment]
Thanks for the shout-out!

For what it's worth, I don't think that this plugin is all that useful for upstream, it's site-specific (really YouTube-specific right now).

**Comment by orschiro** [comment]
> For what it's worth, I don't think that this plugin is all that useful for upstream, it's site-specific (really YouTube-specific right now).

Well let's see! :-)

How much work is it adding more websites?

**Comment by otommod** [comment]
I'm gonna close this.  The upstream issue is WONTFIX and there's the `enable-media-session-service` flag, which sucks, but does provide a "browser-wide" MPRIS interface.
