### ISSUE TITLE
YouTube video playing but player status says "paused"

### ISSUE THREAD

**Issue by orschiro** [otommod/chrome-mpris2#9]
Need to test more when and why this happens but basically:

1. Play a video
2. Check the status of the player and it will show "paused" instead of "playing"

Once I change the status via the player at least once, the player starts refreshing correctly. 

Screencast: https://drive.google.com/file/d/1i79JmqQ5sC3aKR6wnjM_eXdwQOuDjsLa/view

Anyone else with a similar behaviour?

**Comment by otommod** [comment]
I can reproduce as well.

**Comment by orschiro** [comment]
@otommod thanks for testing! Any idea what could cause this?

**Comment by logix2** [comment]
This also happens to me. Here's how this goes: if I go to the YouTube homepage, then click a video, the media player controls in Gnome Shell look like no video is playing in YouTube (but there is a YouTube entry in the MPRIS2 extension I'm using). As soon as I change the YouTube video state or switch to a new video (directly click on another video), this works correctly.

**Comment by otommod** [comment]
I know, there's some issue with the events; in particular, the "play" or "playing" fires before we begin listening to it.  This seems to be because we set up and tear down the listeners whenever a page is changed, while YouTube actually keeps the `<video>` around and reuses it.

**Comment by logix2** [comment]
One more thing, in case this helps. This bug happens in Gnome Shell (Ubuntu 18.04) for me, but not in Linux Mint 18.3 with Cinnamon (3.6.6).

**Comment by logix2** [comment]
There seems to be a somewhat similar issue with reloading the same video too. In Gnome Shell (Ubuntu 18.04), reloading a video makes the video stop loading (Chrome can no longer load the video no matter how many times I refresh it) while the MPRIS2 controls show the video as playing. In Linux Mint 18 with Cinnamon, the video loads upon refreshing a YouTube video page, but the MPRIS2 controls show the video as stopped.

**Comment by logix2** [comment]
This bug no longer happens for me after getting the latest browser-mpris2 from Git.

**Comment by otommod** [comment]
Oh yeah, now it always sets the status to "playing" when a new video starts.  This may be the wrong assumption though, when youtube starts on a new tab (in the background)

**Comment by orschiro** [comment]
Dear all, 

I can confirm it's working properly now. 

Thank you so much!
